### ISSUE TITLE
modify base/validator/update_scores() for tensor handling

### ISSUE THREAD

**Issue by waynemystir** [vn-automata/bt-automata#40]
Keith reported this from Greg rizzo

![image](https://github.com/vn-automata/bt-automata/assets/2120096/cdf3ab2b-3818-4c20-bdb7-f1aa31a26d12)

Looks at a typical warning from PyTorch. Not urgent but we should fix this soon.

**Comment by crazydevlegend** [comment]
it's from the subnet template code, so we could issue a PR in the official template repo, too
i believe it's gotta be a quick fix
